#!/usr/bin/env python3
"""Write notes/transcript-excerpts.md from the recorded calls.

Every prompt and reply below is copied out of evidence/transcripts/*.jsonl and
evidence/marco-polo.json. Nothing is paraphrased and nothing is omitted, so a
reader can check any claim on the site against the bytes that produced it.
"""
from __future__ import annotations
import json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from marco import locus as L, primer, world


def main() -> int:
    frame = primer.expand()
    enc = L.Encoder(frame)
    recs = [json.loads(l)
            for p in sorted((ROOT / "evidence" / "transcripts").glob("probe-*.jsonl"))
            for l in p.read_text().splitlines() if l.strip()]
    polo = json.loads((ROOT / "evidence" / "marco-polo.json").read_text())

    out = ["# Real transcripts",
           "",
           "Generated by `scripts/16_transcripts.py` from `evidence/transcripts/*.jsonl`",
           "and `evidence/marco-polo.json`. Each entry is the exact prompt a model",
           "received and the exact text it returned. Nothing is paraphrased.",
           "",
           f"Primer fingerprint `{frame.fingerprint()}`.",
           "",
           "## The whole input",
           "",
           "One place, one prompt, one reply. The prompt contains the 45 statements",
           "with their plain readings, the place in ordinary English, the instruction,",
           "and the reply schema. Nothing else. No place name, no other model's answer,",
           "no mention that other models exist.",
           ""]

    def find(place, model):
        for r in recs:
            if r.get("situation_id") == place and r.get("model") == model and r.get("ok"):
                return r
        return None

    for place, model in [("shared_workshop", "deepseek-v4.1-flash"),
                         ("shared_workshop", "gpt-6-luna"),
                         ("kitchen_with_friend", "glm-5.3"),
                         ("kitchen_with_friend", "mimo-v2.6-pro")]:
        r = find(place, model)
        if not r:
            continue
        root = L.commit(r["landmarks"])
        out += [f"### {model} · {place}", "",
                "**Prompt, verbatim:**", "", "```text", r["prompt"], "```", "",
                "**Reply, verbatim:**", "", "```json", r["raw_response"].strip(), "```", "",
                f"{r.get('n_selected')} statements chosen. Root `!{root}`.", ""]

    out += ["## The places the models were shown", "",
            "These paragraphs are the only thing that differed between calls.", ""]
    for name, desc in world.DESCRIPTIONS.items():
        out += [f"**{name}** \u2014 {desc}", ""]

    out += ["## The live MARCO/POLO exchange", "",
            f"Hider model `{polo['hider_model']}`. It was told which place it was in and",
            "was never asked to name it.", "",
            f"Opening disclosure `{polo['opening_address']}` "
            f"({polo['disclosure_steps'][0]} of 45 axes).", ""]
    for ev in polo["trace"]:
        if ev["kind"] == "answer":
            out += [f"**Question put to the hider:** `{ev['question']}`", "",
                    "**Reply, verbatim:**", "", "```text", (ev.get("raw") or "").strip(),
                    "```", ""]
        elif ev["kind"] == "disclosure":
            out += [f"**Disclosure:** `{ev['address']}` ({ev['axes']} of 45 axes).", ""]
    full = enc.encode(world.build(polo["place_under_test"]).observations())
    out += [f"The seeker then rebuilt the coordinate itself and compared the root. "
            f"The root of the place is `!{full.commitment}`.", "",
            f"Verdict `{polo['verdict']}`, verified `{str(polo['verified']).lower()}`, "
            f"{polo['questions_asked']} question, {polo['hider_calls']} model call.", ""]

    (ROOT / "notes" / "transcript-excerpts.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote notes/transcript-excerpts.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
